# D-Robotics RDK X5 BSP layer for OpenEmbedded/Yocto Wrynose.
BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "d-robotics"
BBFILE_PATTERN_d-robotics = "^${LAYERDIR}/"
BBFILE_PRIORITY_d-robotics = "7"

LAYERVERSION_d-robotics = "1"
LAYERDEPENDS_d-robotics = "core"
LAYERSERIES_COMPAT_d-robotics = "wrynose"
